app:
  clients:
    hostName: localhost
    scheme: http
    httpPort: 9200
  index:
    name: employee-search
    shard: 2
    replica: 1
    from: 0
    size: 5
    timeout: 60

server:
  port: 8093

spring:
  application:
    name: restworkmanagement