spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restdb
    username: root
    password: dtu@1234
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
    generate-ddl: true
    show-sql: true

server:
  port: 8092

logging:
  level:
    org.springframework: DEBUG